[package]
name = "taimi_hud"
authors = [ "kittywitch" ]
description = "Timers, markers and pathing, eventually."
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
log = "0.4.21"
nexus = { git = "https://github.com/zerthox/nexus-rs", features = ["log", "log_filter", "mumble", "arc", "extras"] }
tokio = { version = "1.43.0", features = [ "full" ] }
arcdps = { git = "https://github.com/zerthox/arcdps-rs", tag = "0.15.1" }
glam = { version = "0.30.0", features = [ "serde" ] }
palette = { version = "0.7.6", features = [ "serde" ] }
serde = { version = "1.0", features = ["derive"] }
glob = "0.3.2"
serde_json = "1.0.140"
serde_jsonrc = { version = "0.1.0", features = [ "preserve_order"] }
serde_with = "3.12.0"
json-strip-comments = "1.0.4"
strum = "0.27.1"
strum_macros = "0.27.1"

[lib]
crate-type = ["cdylib"] # nexus addons are dynamic system libraries (dll)
