name: Cargo Build & Test

on:
  push:
  pull_request:

env: 
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: windows-latest
    strategy:
      matrix:
        toolchain:
          - stable
  steps:
      - uses: actions/checkout@v4
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo build --verbose
      - run: cargo test --verbose
      - uses: actions/upload-artifact@v4
        with:
          name: TaimiHUD.dll
          path: target/x86_64-pc-windows-gnu/debug/TaimiHUD.dll
